name: Build and Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'openjdk' #adoptopenjdk

    - name: Build with Maven
      run: mvn clean package

    #- name: Run tests (optional)
    #  run: mvn test

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-java-app
        path: target/*.jar
